version: "3.8"

services:
    backend:
        build: ./backend
        container_name: recipe_backend
        ports:
            - "5000:5000"
        env_file:
            - ./backend/.env
        networks:
            - recipe_net

    frontend:
        build: ./frontend
        container_name: recipe_frontend
        ports:
            - "3000:80" # map Nginx port 80 -> localhost:3000
        environment:
            - REACT_APP_API_URL=http://backend:5000
        depends_on:
            - backend
        networks:
            - recipe_net

networks:
    recipe_net:
