require("dotenv").config();
const mongoose = require("mongoose");
const Recipe = require("../models/Recipe");

mongoose
    .connect(process.env.MONGO_URI)
    .then(() => {
        console.log("Kết nối MongoDB thành công");

        return Recipe.insertMany([
            {
                title: "Gà sốt Bourbon",
                description:
                    "Món gà áp chảo kiểu Mỹ, mềm ngọt, đậm đà với sốt gừng, tỏi và nước tương.",
                ingredients: [
                    "500g ức gà hoặc đùi gà không xương",
                    "2 muỗng canh nước tương",
                    "2 muỗng canh đường nâu",
                    "1 muỗng canh giấm táo (hoặc giấm gạo)",
                    "1 muỗng canh rượu bourbon (có thể thay bằng nước táo)",
                    "2 tép tỏi băm",
                    "1 muỗng cà phê gừng băm",
                    "1 muỗng cà phê bột bắp (để tạo độ sánh)",
                    "Dầu ăn, tiêu, hành lá",
                ],
                steps: [
                    "Cắt gà thành miếng nhỏ, ướp với một ít nước tương và tiêu trong 15 phút.",
                    "Áp chảo gà cho vàng đều hai mặt.",
                    "Trộn nước tương, đường nâu, giấm, rượu, tỏi, gừng trong một chén.",
                    "Đổ hỗn hợp sốt vào chảo, đun nhỏ lửa cho đến khi gà chín và sốt sánh lại.",
                    "Cho bột bắp pha loãng vào nếu muốn sánh hơn, rắc hành lá và dọn ra.",
                ],
                imageThumb:
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235264/MwuCd6HpQ5mDvn4OLRkA_0S9A9886_rgnhkt.webp",
                images: [
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235263/EYkqUO7OQ8GmSqh8Z3IO_Bourbon_Chicken_ktzlxe.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235259/KBhtHmrqSXew6wG5h50c_IMG-20160320-WA0002_khmnnz.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235260/iMkILh3ZSMO9oS6JkEQ9_20180325_185213_dujwqb.webp",
                ],
                videoUrl: "https://www.youtube.com/watch?v=BPJ4C9hWBCs",
                category: "main",
                categoryDisplay: "Món chính",
                cookingTime: "30 phút",
                serves: 3,
                tags: ["gà", "sốt ngọt", "kiểu Mỹ"],
                calories: 380,
                views: 0,
                likes: 0,
                origin: "Mỹ",
                comments: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                isPublished: true,
                createdBy: "683e705ea69063a60c1401ed",
            },

            {
                title: "Bánh mì chuối mềm thơm",
                description:
                    "Món bánh mì chuối mềm mịn, ngọt dịu tự nhiên từ chuối chín – cực kỳ đơn giản nhưng thơm ngon khó cưỡng.",
                ingredients: [
                    "3 quả chuối chín",
                    "2 quả trứng",
                    "100g đường nâu (hoặc đường trắng)",
                    "60ml dầu ăn (hoặc bơ tan chảy)",
                    "1 muỗng cà phê vanilla",
                    "1/2 muỗng cà phê muối",
                    "1 muỗng cà phê bột nở (baking powder)",
                    "1/2 muỗng cà phê baking soda",
                    "180g bột mì đa dụng",
                    "Tùy chọn: hạt óc chó, chocolate chip",
                ],
                steps: [
                    "Dằm nhuyễn chuối chín trong tô lớn.",
                    "Thêm trứng, đường, dầu ăn, vanilla và trộn đều.",
                    "Rây bột mì, muối, baking powder và baking soda vào hỗn hợp, trộn nhẹ tay.",
                    "Cho vào khuôn nướng đã lót giấy nến hoặc chống dính.",
                    "Nướng ở 175°C (350°F) trong 50–60 phút đến khi chín vàng và que xiên không dính bột.",
                    "Để nguội và thưởng thức – bánh ngon hơn sau 1 ngày!",
                ],
                imageThumb:
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235431/wBZxNua1T8yfDwbfo9Fz_0S9A9315_fnpsqu.webp",
                images: [
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235428/klAWzgS96FaiDaqpNLig_image_ekiqnc.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235427/xeKul9ZdTxKTXs3IGs16_20170323_193853_uvw1m8.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235427/0AN9rGc7QE6NZq2DRh4v_20181107_181703_nwgqen.webp",
                ],
                videoUrl: "https://www.youtube.com/watch?v=QzLBBnqz4rQ",
                category: "baking",
                categoryDisplay: "Nướng lò",
                cookingTime: "1 giờ",
                serves: 6,
                tags: ["bánh chuối", "ngọt", "tráng miệng"],
                calories: 290,
                views: 0,
                likes: 0,
                origin: "Mỹ",
                comments: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                isPublished: true,
                createdBy: "683e705ea69063a60c1401ed",
            },
            {
                title: "Gà hầm đậu đen và phô mai kem",
                description:
                    "Món gà nấu chậm kiểu Mỹ với đậu đen, sốt salsa và phô mai kem béo mịn – mềm ngọt, thơm lừng, ăn kèm cơm hay bánh đều ngon.",
                ingredients: [
                    "500g ức gà hoặc đùi gà không xương",
                    "1 hộp đậu đen (black beans) đã lọc nước",
                    "1 hũ salsa cà chua (hoặc ớt chuông, hành tây xay)",
                    "100g phô mai kem (cream cheese)",
                    "1/2 muỗng cà phê bột ớt (nếu thích cay)",
                    "1/2 muỗng cà phê tiêu",
                    "1/2 muỗng cà phê muối",
                    "1/2 củ hành tây (tùy chọn)",
                    "Ngò hoặc rau mùi để rắc sau khi nấu",
                ],
                steps: [
                    "Cho gà, đậu đen, salsa, hành tây, gia vị vào nồi hầm (hoặc nồi điện nấu chậm Crock-Pot).",
                    "Đậy nắp và nấu ở chế độ thấp (low) khoảng 6–8 tiếng hoặc cao (high) 3–4 tiếng.",
                    "30 phút cuối, thêm phô mai kem vào, đậy nắp và đợi tan chảy.",
                    "Khi gà đã chín mềm, dùng nĩa xé nhỏ và trộn đều với phần sốt.",
                    "Ăn kèm với cơm, bánh tortilla hoặc bánh mì tùy thích.",
                ],
                imageThumb:
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235645/uxMwt1VGQ5m2ePyzwHWy_salsa-chicken-black-beans-2312_nb5eid.webp",
                images: [
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235643/picL5ADeK_q1xzn3.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235642/hOfGrmmERy2S08C2m31Q_salsa-chicken-black-beans-2331_njjenw.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235621/Gg7PXFTIQWGkPYJiZ3Oo_image_odybei.webp",
                ],
                videoUrl: "https://www.youtube.com/watch?v=3IztRA8uZ6Q",
                category: "main",
                categoryDisplay: "Món chính",
                cookingTime: "8 giờ",
                serves: 4,
                tags: ["gà hầm", "kem phô mai", "đậu đen", "slow-cooker"],
                calories: 430,
                views: 0,
                likes: 0,
                origin: "Mỹ",
                comments: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                isPublished: true,
                createdBy: "683e705ea69063a60c1401ed",
            },
            {
                title: "Mì Ý gà sốt kem Cajun",
                description:
                    "Món mì Ý kiểu Mỹ với thịt gà đậm vị Cajun, hòa quyện trong nước sốt kem béo mịn – cay nhẹ, thơm nức, cực kỳ hấp dẫn.",
                ingredients: [
                    "250g ức gà",
                    "200g mì fettuccine (hoặc mì ống)",
                    "1 muỗng canh gia vị Cajun",
                    "1 muỗng canh dầu olive",
                    "2 tép tỏi băm",
                    "200ml kem tươi (whipping cream)",
                    "30g phô mai Parmesan bào",
                    "1/2 quả ớt chuông đỏ (thái sợi)",
                    "1/2 quả ớt chuông vàng (thái sợi)",
                    "Muối, tiêu, rau mùi tây (tùy chọn)",
                ],
                steps: [
                    "Ướp ức gà với gia vị Cajun và ít muối tiêu trong 15 phút.",
                    "Luộc mì theo hướng dẫn, để ráo nước.",
                    "Áp chảo gà chín vàng hai mặt rồi thái lát.",
                    "Phi tỏi với dầu, cho ớt chuông vào xào nhanh, đổ kem tươi vào đun nhỏ lửa.",
                    "Thêm phô mai Parmesan, khuấy tan. Nêm thêm Cajun nếu muốn.",
                    "Cho mì và gà đã thái vào sốt, trộn đều và rắc rau mùi tây lên.",
                ],
                imageThumb:
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235818/VPeSMiYHRce4BWsyj7Nl_0S9A5582_rjncxm.webp",
                images: [
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235817/WHnfAAGES8qMRC5hA4sw_IMG_20170417_052205224_HDR-7000x3937_ynkeen.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235811/picscds0W_pjuhum.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235809/piccZDaro_ckc9yr.webp",
                ],
                videoUrl: "https://www.youtube.com/watch?v=acjHsHbBlbY",
                category: "noodles",
                categoryDisplay: "Mì & Bún",
                cookingTime: "35 phút",
                serves: 2,
                tags: ["mì Ý", "gà", "Cajun", "kem"],
                calories: 520,
                views: 0,
                likes: 0,
                origin: "Mỹ",
                comments: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                isPublished: true,
                createdBy: "683e705ea69063a60c1401ed",
            },
            {
                title: "Bánh quy yến mạch nho khô",
                description:
                    "Bánh quy mềm, thơm mùi quế và vani, giàu chất xơ từ yến mạch và ngọt dịu từ nho khô – món ăn vặt lành mạnh và ngon miệng.",
                ingredients: [
                    "120g bơ lạt (để mềm ở nhiệt độ phòng)",
                    "100g đường nâu",
                    "50g đường trắng",
                    "1 quả trứng",
                    "1 muỗng cà phê vani",
                    "100g bột mì đa dụng",
                    "1/2 muỗng cà phê baking soda",
                    "1/2 muỗng cà phê bột quế",
                    "1/4 muỗng cà phê muối",
                    "100g yến mạch cán (rolled oats)",
                    "80g nho khô",
                ],
                steps: [
                    "Đánh bơ, đường nâu và đường trắng cho mịn.",
                    "Thêm trứng và vani, đánh đều.",
                    "Rây bột mì, baking soda, quế và muối vào, trộn đều.",
                    "Cho yến mạch và nho khô vào, trộn đến khi hòa quyện.",
                    "Múc từng viên nhỏ lên khay có lót giấy nến.",
                    "Nướng ở 175°C (350°F) trong 10–12 phút đến khi viền bánh vàng nhẹ.",
                    "Để nguội và bảo quản trong hộp kín.",
                ],
                imageThumb:
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236000/KU3JVxMDRriISEG3KdPy_0S9A9740_v9lgoa.webp",
                images: [
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235991/WX0S1zIRQoGDjj6TdHnp_153212351478628184725256681952_w8qvku.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235989/CJuh7C3QJS2he8CHISg8_0S9A9731_tlh6ra.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748235989/tDxRW7TeQsKEbvZ6MTjl_IMG_1468_hoq2po.jpg",
                ],
                videoUrl: "https://www.youtube.com/watch?v=kG_pDkFaW0M",
                category: "baking",
                categoryDisplay: "Nướng lò",
                cookingTime: "25 phút",
                serves: 4,
                tags: ["bánh quy", "yến mạch", "nho khô", "ăn vặt"],
                calories: 150,
                views: 0,
                likes: 0,
                origin: "Mỹ",
                comments: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                isPublished: true,
                createdBy: "683e705ea69063a60c1401ed",
            },
            {
                title: "Bánh chuối phủ kem phô mai",
                description:
                    "Chiếc bánh chuối ẩm mịn, thơm ngọt tự nhiên từ chuối chín, kết hợp lớp kem phô mai béo mịn ở trên — hoàn hảo cho mọi dịp.",
                ingredients: [
                    "2–3 quả chuối chín nghiền nhuyễn",
                    "2 quả trứng",
                    "150g đường",
                    "100ml dầu ăn (hoặc bơ tan chảy)",
                    "1 muỗng cà phê vanilla",
                    "1/2 muỗng cà phê muối",
                    "1 muỗng cà phê baking soda",
                    "1 muỗng cà phê bột nở (baking powder)",
                    "200g bột mì đa dụng",
                    "120ml sữa chua hoặc sữa tươi",
                    "— Phần kem phủ —",
                    "100g kem phô mai (cream cheese, để mềm)",
                    "50g bơ lạt (mềm)",
                    "60g đường bột",
                    "1/2 muỗng cà phê vani",
                ],
                steps: [
                    "Trộn chuối, trứng, đường, dầu ăn, vani cho hòa quyện.",
                    "Rây bột mì, muối, baking soda, baking powder vào hỗn hợp chuối, thêm sữa chua và trộn đều.",
                    "Đổ bột vào khuôn, nướng ở 175°C trong 35–45 phút.",
                    "Trong lúc bánh nguội, đánh kem phô mai + bơ + đường bột + vani cho mịn.",
                    "Phết kem phủ lên mặt bánh sau khi bánh đã nguội hoàn toàn.",
                    "Bảo quản bánh trong ngăn mát tủ lạnh, dùng trong 2–3 ngày.",
                ],
                imageThumb:
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236257/ErcPhaBVS2OMnh07iiZf_banana-cake-with-cream-cheese-frosting-08_cfe7mb.webp",
                images: [
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236260/qax7Bn7SnCZm6DccRezo_IMG_2667_dopktz.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236254/01485847540_mgndsk.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236253/3mlBLlbURm696DfN8yuM_IMG_1125_aka7wl.webp",
                ],
                videoUrl: "https://www.youtube.com/watch?v=7eZ7OnmtV6s",
                category: "baking",
                categoryDisplay: "Nướng lò",
                cookingTime: "1 giờ",
                serves: 6,
                tags: ["bánh chuối", "kem phô mai", "tráng miệng"],
                calories: 420,
                views: 0,
                likes: 0,
                origin: "Mỹ",
                comments: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                isPublished: true,
                createdBy: "683e705ea69063a60c1401ed",
            },
            {
                title: "Thịt nướng kiểu Mỹ",
                description:
                    "Món thịt nướng đậm đà kiểu Mỹ – mềm, mọng nước, phủ sốt cà ngọt nhẹ, cực kỳ lý tưởng cho bữa tối gia đình.",
                ingredients: [
                    "500g thịt bò xay (hoặc trộn với thịt heo xay)",
                    "1 quả trứng",
                    "1/2 củ hành tây băm nhỏ",
                    "1/2 chén sữa tươi",
                    "1/2 chén vụn bánh mì (hoặc bánh mì khô xay)",
                    "2 muỗng canh sốt cà chua (ketchup)",
                    "1 muỗng canh mù tạt vàng (tùy chọn)",
                    "1 muỗng cà phê muối",
                    "1/2 muỗng cà phê tiêu",
                    "1/2 muỗng cà phê tỏi bột",
                    "— Sốt phủ mặt —",
                    "3 muỗng canh ketchup",
                    "1 muỗng canh đường nâu",
                    "1 muỗng cà phê giấm táo",
                ],
                steps: [
                    "Trộn đều tất cả nguyên liệu phần thịt trong tô lớn (không trộn quá kỹ).",
                    "Đổ hỗn hợp vào khuôn loaf (khuôn bánh mì dài), ép nhẹ.",
                    "Trộn nguyên liệu phần sốt phủ rồi phết đều lên mặt thịt.",
                    "Nướng ở 175°C trong 50–60 phút.",
                    "Để nghỉ 10 phút trước khi cắt lát và dùng kèm khoai tây nghiền hoặc rau củ hấp.",
                ],
                imageThumb:
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236350/1O1KC1wTKTskFlseYbws_0S9A6432_ni75ln.webp",
                images: [
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236376/uTzl5N1wSE68ETtWNRZe-026-virginia-meatloaf_el33pk.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236355/P3ARuorWTcC89UFWIKvr_77D4F649-3082-4CCF-9D34-7D0545791ABE_n1pssa.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236350/IL9azIqWTa2owvUP4fpR_0S9A6427_axjoam.webp",
                ],
                videoUrl: "https://www.youtube.com/watch?v=-t7gZ1OLVJQ",
                category: "main",
                categoryDisplay: "Món chính",
                cookingTime: "1 giờ",
                serves: 4,
                tags: ["thịt nướng", "meatloaf", "kiểu Mỹ", "ketchup"],
                calories: 480,
                views: 0,
                likes: 0,
                origin: "Mỹ",
                comments: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                isPublished: true,
                createdBy: "683e705ea69063a60c1401ed",
            },
            {
                title: "Mì Ý sốt bò nổi tiếng kiểu Jo Mama",
                description:
                    "Món mì Ý sốt cà thịt bằm đậm đà kiểu Mỹ – hương vị gia đình truyền thống, nổi tiếng với nước sốt nấu chậm thơm nức và ngon khó cưỡng.",
                ingredients: [
                    "400g mì Ý (spaghetti)",
                    "500g thịt bò xay",
                    "1 củ hành tây băm nhỏ",
                    "4 tép tỏi băm",
                    "1 hộp cà chua nghiền (400g)",
                    "2 muỗng canh sốt cà chua (ketchup hoặc tomato paste)",
                    "1 muỗng cà phê đường",
                    "1 muỗng cà phê oregano khô",
                    "1/2 muỗng cà phê basil (húng quế khô)",
                    "Muối, tiêu, dầu olive",
                    "Phô mai Parmesan bào (tùy chọn)",
                ],

                steps: [
                    "Luộc mì Ý theo hướng dẫn trên bao bì, để ráo.",
                    "Phi hành và tỏi trong dầu olive cho thơm, cho thịt bò vào xào chín.",
                    "Thêm cà chua nghiền, ketchup, đường, gia vị khô, muối và tiêu.",
                    "Nấu nhỏ lửa ít nhất 30 phút để sốt đậm đà và sệt lại.",
                    "Cho mì vào dĩa, rưới sốt lên, rắc Parmesan nếu thích. Dùng nóng.",
                ],
                imageThumb:
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236539/xy39o2sOTtudkgyDgZtv_spaghettisauce_iztgvm.webp",
                images: [
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236481/I4FPiyFMTxW3pcAcQ77F_JMWFS_5_-_final_2_yeqtqd.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236479/bMWnCGreSgeji8rnPIAp_JMWFS_4_-_final_1_-_horizontal_maotbe.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236475/01488472716_r5jcxh.webp",
                ],
                videoUrl: "https://www.youtube.com/watch?v=r37U4AAjOqg",
                category: "noodles",
                categoryDisplay: "Mì & Bún",
                cookingTime: "45 phút",
                serves: 4,
                tags: ["mì Ý", "sốt bò", "cà chua", "pasta"],
                calories: 520,
                views: 0,
                likes: 0,
                origin: "Mỹ",
                comments: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                isPublished: true,
                createdBy: "683e705ea69063a60c1401ed",
            },
            {
                title: "Brownies tùy biến siêu ngon",
                description:
                    "Món brownies mềm ẩm, đậm vị socola với công thức cơ bản có thể thêm bất cứ thứ gì bạn thích: hạt, trái cây khô, chocolate chip, dừa vụn… đúng kiểu 'whatever floats your boat'!",
                ingredients: [
                    "120g bơ lạt (để mềm)",
                    "150g đường",
                    "2 quả trứng",
                    "1 muỗng cà phê vanilla",
                    "50g bột cacao không đường",
                    "70g bột mì đa dụng",
                    "1/4 muỗng cà phê muối",
                    "1/4 muỗng cà phê baking powder",
                    "Tùy chọn: 1 nắm chocolate chips, hạt óc chó, hạnh nhân, dừa sấy, nho khô...",
                ],
                steps: [
                    "Làm nóng lò ở 175°C (350°F). Lót giấy nến vào khuôn vuông 20x20cm.",
                    "Đánh bơ với đường cho hòa quyện, thêm trứng và vanilla, khuấy đều.",
                    "Rây bột cacao, bột mì, muối, baking powder vào hỗn hợp trên và trộn đều.",
                    "Thêm các nguyên liệu tùy chọn (chocolate chips, hạt, trái cây khô...).",
                    "Đổ bột vào khuôn, dàn đều mặt, nướng khoảng 20–25 phút hoặc đến khi se mặt.",
                    "Để nguội, cắt miếng vuông và thưởng thức!",
                ],
                imageThumb:
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236842/i9r15r47TKCWswvpulSQ_0S9A5670_ikes0g.webp",
                images: [
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236844/yX79JawzR3CHcGEGWh4I_0S9A5678_rq4wcs.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236840/VURHnjkFRCm0kC5isv29_0S9A5699_ld4luv.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236838/UIL7sEjRs25jlPU0dVgW_9B8FDFC2-5272-44CB-AF50-F10DAFB05047_xlfurp.webp",
                ],
                videoUrl: "https://www.youtube.com/watch?v=dzVfXQsDPJ4",
                category: "baking",
                categoryDisplay: "Nướng lò",
                cookingTime: "30 phút",
                serves: 6,
                tags: ["brownies", "socola", "tuỳ biến", "tráng miệng"],
                calories: 320,
                views: 0,
                likes: 0,
                origin: "Mỹ",
                comments: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                isPublished: true,
                createdBy: "683e705ea69063a60c1401ed",
            },
            {
                title: "Bánh kếp mềm xốp",
                description:
                    "Bánh kếp truyền thống kiểu Mỹ – mềm xốp, thơm nhẹ mùi vani và bơ, dùng kèm mật ong hoặc trái cây đều tuyệt vời cho bữa sáng.",
                ingredients: [
                    "130g bột mì đa dụng",
                    "2 muỗng canh đường",
                    "1 muỗng cà phê bột nở (baking powder)",
                    "1/4 muỗng cà phê muối",
                    "1 quả trứng",
                    "180ml sữa tươi không đường",
                    "30g bơ lạt (đun chảy)",
                    "1/2 muỗng cà phê vanilla",
                ],
                steps: [
                    "Trộn bột mì, đường, muối và bột nở trong tô lớn.",
                    "Trong tô khác, đánh trứng với sữa, vanilla và bơ tan chảy.",
                    "Đổ hỗn hợp ướt vào khô, khuấy nhẹ tay đến khi bột hòa quyện (không trộn quá kỹ).",
                    "Đun nóng chảo chống dính, phết chút bơ. Múc từng muỗng bột vào chảo.",
                    "Khi mặt bánh nổi bọt khí và hơi khô viền, lật mặt, chiên thêm 1–2 phút.",
                    "Ăn kèm với mật ong, siro cây phong hoặc trái cây tươi tùy thích.",
                ],
                imageThumb:
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236626/picwslJ1c_s8e6jh.webp",
                images: [
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236696/EapXGCsITlymzixwwuAR_DSC_1008_fc55k7.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236623/pic4IC064_jr95bv.webp",
                    "https://res.cloudinary.com/dclp1x0cw/image/upload/v1748236620/EapXGCsITlymzixwwuAR_DSC_1008_ml2rls.webp",
                ],
                videoUrl: "https://www.youtube.com/watch?v=2LBX5nrU8sk",
                category: "main",
                categoryDisplay: "Món chính",
                cookingTime: "20 phút",
                serves: 3,
                tags: ["pancake", "bánh kếp", "ăn sáng", "mềm xốp"],
                calories: 280,
                views: 0,
                likes: 0,
                origin: "Mỹ",
                comments: [],
                createdAt: new Date(),
                updatedAt: new Date(),
                isPublished: true,
                createdBy: "683e705ea69063a60c1401ed",
            },
        ]);
    })
    .then(() => {
        console.log("Tạo công thức thành công");
        mongoose.disconnect();
    })
    .catch((err) => {
        console.error("Lỗi:", err);
    });
